// Generated from the backend OpenAPI schema. Do not edit manually.

import type { components } from "./generated-schema";

export type ApiSchemas = components["schemas"];

export type AlertSummary = ApiSchemas["AlertSummary"];
export type ArtifactSummary = ApiSchemas["ArtifactSummary"];
export type AuditEventResponse = ApiSchemas["AuditEventResponse"];
export type BacktestFrameResponse = ApiSchemas["BacktestFrameResponse"];
export type BacktestRunResponse = ApiSchemas["BacktestRunResponse"];
export type BacktestRunSummary = ApiSchemas["BacktestRunSummary"];
export type CapitalAllocationResponse = ApiSchemas["CapitalAllocationResponse"];
export type CapitalBudgetSummaryResponse = ApiSchemas["CapitalBudgetSummaryResponse"];
export type CapitalRebalanceRequest = ApiSchemas["CapitalRebalanceRequest"];
export type CapitalUsageSnapshotResponse = ApiSchemas["CapitalUsageSnapshotResponse"];
export type DealHistoryEntryResponse = ApiSchemas["DealHistoryEntryResponse"];
export type DeskDefinitionResponse = ApiSchemas["DeskDefinitionResponse"];
export type DeskSnapshotResponse = ApiSchemas["DeskSnapshotResponse"];
export type ExecutionFillResponse = ApiSchemas["ExecutionFillResponse"];
export type ExecutionGuardDecisionResponse = ApiSchemas["ExecutionGuardDecisionResponse"];
export type ExecutionPreviewResponse = ApiSchemas["ExecutionPreviewResponse"];
export type ExecutionRequest = ApiSchemas["ExecutionRequest"];
export type ExecutionResultResponse = ApiSchemas["ExecutionResultResponse"];
export type HTTPValidationError = ApiSchemas["HTTPValidationError"];
export type HeadlineRiskPointResponse = ApiSchemas["HeadlineRiskPointResponse"];
export type HealthResponse = ApiSchemas["HealthResponse"];
export type HealthDependenciesResponse = {
  status: string;
  generated_at: string;
  portfolio_slug: string;
  dependencies: Record<string, unknown>;
};
export type HistoricalStressExtremeResponse = ApiSchemas["HistoricalStressExtremeResponse"];
export type HoldingSnapshotResponse = ApiSchemas["HoldingSnapshotResponse"];
export type InstrumentDefinitionResponse = ApiSchemas["InstrumentDefinitionResponse"];
export type LiveRiskSummaryResponse = ApiSchemas["LiveRiskSummaryResponse"];
export type MT5AccountSnapshotResponse = ApiSchemas["MT5AccountSnapshotResponse"];
export type MT5LiveEventChangeSummaryResponse = ApiSchemas["MT5LiveEventChangeSummaryResponse"];
export type MT5LiveEventResponse = ApiSchemas["MT5LiveEventResponse"];
export type MT5PendingOrderResponse = ApiSchemas["MT5PendingOrderResponse"];
export type MT5PositionResponse = ApiSchemas["MT5PositionResponse"];
export type MT5TerminalStatusResponse = ApiSchemas["MT5TerminalStatusResponse"];
export type MT5TickResponse = ApiSchemas["MT5TickResponse"];
export type MarketDataSyncRequest = ApiSchemas["MarketDataSyncRequest"];
export type MarketDataSyncStatusResponse = ApiSchemas["MarketDataSyncStatusResponse"];
export type ModelCapitalBudgetResponse = ApiSchemas["ModelCapitalBudgetResponse"];
export type ModelComparisonResponse = ApiSchemas["ModelComparisonResponse"];
export type OperatorRunResponse = {
  id: number;
  portfolio_id?: number | null;
  portfolio_slug?: string | null;
  action: string;
  request_id: string;
  status: string;
  stage: string;
  request_payload: Record<string, unknown>;
  artifact_refs: Record<string, unknown>;
  result: Record<string, unknown>;
  error_code?: string | null;
  error_message?: string | null;
  hint?: string | null;
  queue_task_id?: string | null;
  reused_run_id?: number | null;
  reused?: boolean;
  elapsed_seconds?: number | null;
  is_stale?: boolean;
  poll_after_ms?: number | null;
  started_at?: string | null;
  finished_at?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};
export type OperatorAlertResponse = ApiSchemas["OperatorAlertResponse"];
export type OrderHistoryEntryResponse = ApiSchemas["OrderHistoryEntryResponse"];
export type PortfolioCapitalSliceResponse = ApiSchemas["PortfolioCapitalSliceResponse"];
export type PortfolioExposureItemResponse = ApiSchemas["PortfolioExposureItemResponse"];
export type PortfolioExposureResponse = ApiSchemas["PortfolioExposureResponse"];
export type PortfolioSummary = ApiSchemas["PortfolioSummary"];
export type ReallocationRecommendationResponse = ApiSchemas["ReallocationRecommendationResponse"];
export type ReconciliationAcknowledgeRequest = ApiSchemas["ReconciliationAcknowledgeRequest"];
export type ReconciliationAcknowledgeResponse = ApiSchemas["ReconciliationAcknowledgeResponse"];
export type ReconciliationAcknowledgementResponse = ApiSchemas["ReconciliationAcknowledgementResponse"];
export type ReconciliationIncidentResponse = ApiSchemas["ReconciliationIncidentResponse"];
export type ReconciliationMismatchResponse = ApiSchemas["ReconciliationMismatchResponse"];
export type ReconciliationSummaryResponse = ApiSchemas["ReconciliationSummaryResponse"] & {
  operational_truth?: string | null;
  target_exposure_by_symbol?: Record<string, number>;
  broker_exposure_by_symbol?: Record<string, number>;
  staleness_reason?: string | null;
  active_incident_count?: number;
  resolved_incident_count?: number;
  autoresolved_count?: number;
  live_window_minutes?: number | null;
  heal_window_days?: number | null;
  history_backfill_applied?: boolean;
};
export type MT5LiveStateResponse = Omit<ApiSchemas["MT5LiveStateResponse"], "reconciliation"> & {
  operational_truth?: string | null;
  truth_score?: number | null;
  quality_checks?: Array<Record<string, unknown>>;
  analytics_generated_at?: string | null;
  analytics_stale?: boolean | null;
  reconciliation?: ReconciliationSummaryResponse | null;
};
export type ReportContentResponse = ApiSchemas["ReportContentResponse"] & {
  report_id?: number | null;
};
export type ReportRunResponse = ApiSchemas["ReportRunResponse"];
export type RiskAttributionAssetClassResponse = ApiSchemas["RiskAttributionAssetClassResponse"];
export type RiskAttributionModelResponse = ApiSchemas["RiskAttributionModelResponse"];
export type RiskAttributionPositionResponse = ApiSchemas["RiskAttributionPositionResponse"];
export type RiskAttributionResponse = ApiSchemas["RiskAttributionResponse"];
export type RiskBudgetModelResponse = ApiSchemas["RiskBudgetModelResponse"];
export type RiskBudgetPositionResponse = ApiSchemas["RiskBudgetPositionResponse"];
export type RiskBudgetResponse = ApiSchemas["RiskBudgetResponse"];
export type RiskDataQualityResponse = ApiSchemas["RiskDataQualityResponse"];
export type RiskDecisionResponse = ApiSchemas["RiskDecisionResponse"];
export type RiskDecisionStateResponse = ApiSchemas["RiskDecisionStateResponse"];
export type RunBacktestRequest = ApiSchemas["RunBacktestRequest"];
export type RunReportRequest = ApiSchemas["RunReportRequest"];
export type RunSnapshotRequest = ApiSchemas["RunSnapshotRequest"];
export type RunStressTestRequest = ApiSchemas["RunStressTestRequest"];
export type SnapshotRunResponse = ApiSchemas["SnapshotRunResponse"];
export type SnapshotSummary = ApiSchemas["SnapshotSummary"];
export type StressReportResponse = ApiSchemas["StressReportResponse"];
export type StressScenarioRequest = ApiSchemas["StressScenarioRequest"];
export type StressScenarioResultResponse = ApiSchemas["StressScenarioResultResponse"];
export type TradeProposalRequest = ApiSchemas["TradeProposalRequest"];
export type ValidationError = ApiSchemas["ValidationError"];
export type ValidationRunSummary = ApiSchemas["ValidationRunSummary"];
export type WorkerJobStatusResponse = ApiSchemas["WorkerJobStatusResponse"];
export type WorkerStatusResponse = ApiSchemas["WorkerStatusResponse"];

export type ModelComparisonRow = ApiSchemas["ModelComparisonRow"] & {
  es_acerbi_status?: "PASS" | "WARN" | "FAIL" | "N/A" | null;
  es_acerbi_p_value?: number | null;
  es_acerbi_observations?: number | null;
};
